-- Run these SQL statements in your Supabase SQL Editor to fix truncated poems

-- 1. Stork Moon
UPDATE poems SET
  content = 'There is a stork on the top of this ancient palace
wall that laid a moon in its nest like an egg.
The sultan declared it a national monument
but the people said let it be and time unraveled
and wars were fought and the sultan died
and his son was inaugurated while hands clapped
in the plaza and snake charmers played flute songs
and tourism tripled and the straw of the nest blew away
in the strong Sahara winds. The walls of the palace shrank
into museum walls, adorned with memorabilia,
and when the stork returned with silver fish for its baby
moon, it found a vacant wall
and the habitat unrecognisably gentrified.
The new sultan had come to a compromise
with the people, for he was wise, and had encased
the moon in glass, and set it in orbit, just outside the atmosphere
so that all could see, on this night or another: a gift
to make all his subjects content. And they all were, all except the stork
who, to this day, flies from palace to palace, seeking something
disappeared, gliding over the face of the water, with stretched wings
and the glimmering reflection of the moon under its feathery belly
(a shadow of the heart).',
  plain_text = 'There is a stork on the top of this ancient palace
wall that laid a moon in its nest like an egg.
The sultan declared it a national monument
but the people said let it be and time unraveled
and wars were fought and the sultan died
and his son was inaugurated while hands clapped
in the plaza and snake charmers played flute songs
and tourism tripled and the straw of the nest blew away
in the strong Sahara winds. The walls of the palace shrank
into museum walls, adorned with memorabilia,
and when the stork returned with silver fish for its baby
moon, it found a vacant wall
and the habitat unrecognisably gentrified.
The new sultan had come to a compromise
with the people, for he was wise, and had encased
the moon in glass, and set it in orbit, just outside the atmosphere
so that all could see, on this night or another: a gift
to make all his subjects content. And they all were, all except the stork
who, to this day, flies from palace to palace, seeking something
disappeared, gliding over the face of the water, with stretched wings
and the glimmering reflection of the moon under its feathery belly
(a shadow of the heart).'
WHERE slug = 'stork-moon';

-- 2. The Cave
UPDATE poems SET
  content = 'My grandmother was the sole proprietor of a three room cave, to which we sold tickets and gave tours. She always said, "It''s a funny thing to have built a life upon the absence of Earth". When she died, she left us the cave (my mother had already died in an incident that was unrelated to the cave), and this is how I became the proprietor of one third of a cave which was located just south west of a small town that wasn''t even a tourist destination.

My grandfather, always a pragmatist, found that the work of his evenings revolved around trying to get my grandmother to use the cave for something practical. He was always interested in the yield.

"We can''t just keep giving tours with this little seasonal traffic; bat shit from the floor of the cave won''t miraculously turn it into food," he complained, as he sat at the dining room table, using his fork to prod at white, mushy potatoes. The lumps struck me as oddly resembling the very bat shit which he claimed we couldn''t eat. He shoveled a forkful into his mouth and mashed his chompers up and down. The clumps of bat shit that did not make it past the guard of his lips ended up in his wiry, greasy beard. I gazed at him, wondering how we could squeeze more money out of the emptiness in our backyard.

My grandparents had tried making cheese at one point because cheese and caves go hand in hand like scotch and cellars. They gave it a good go. They accumulated a number of goats. One hairy, black goat, had it not been for movies, would have gotten off scot free from being the devil. But instead, the unlucky goat, who just wanted attention from us children, was painted with the name Phil and cast into a life of neglect, depression, and loneliness. Phil only produced one rind of cheese in his life, and it was never eaten. Instead it was left in the cellar where it grew horns of green mold and later became the feature event of a slow year.

When I grew up, the mountains called me, probably because I had spent so many hours underground. As I stumbled up the rocks, I couldn''t help consider that part of my equity contained a third of a cave. Nonetheless, on my thirtieth birthday, from the peaks of a medium sized mountain, I looked out over small drips of other mountains in this particular range. I studied the shadows from the sun and layers upon layers of rocks and clouds. I had come so far from the cave of my childhood. A memory occurred to me then, as if the thin threads of cirrus clouds were weaving images in my mind like a loom.

I wasn''t sure if the memory was mine or was patched together from television shows, recordings my father had captured, subconscious dreams, etc. I couldn''t figure out why my grandmother had been so happy with nothing at all. In my memory, my grandmother trounced around the kitchen, cooking, surrounded by almost nothing: a few potatoes, a can of corn, a tin of sardines, a rutabaga, the milk from the goats, and some magical ingredients, the name of which she refused to disclose (us children all agreed it was bat shit or scrapings off the hooves of the goats or mashed up hair). As I watched her dance around the kitchen, blissfully ignorant of our poverty, my grandmother, every so often, glanced out the window above the sink at the entrance to our cave, as if waiting for a beast to emerge. One of her idiosyncrasies was that she refused to put the lids of jars back on the jars after she opened them. She also slept with the door to her bedroom open. Perhaps, I remembered, everything, to her, was a cave.

I descended the mountain and went back home and sat in the cave. Although I could have forcedly conjured some revelation by sitting cross legged like a yogi in the cold, damp, dark hollow, underground, I didn''t. Instead my mind felt as empty as the three rooms of the cave. I walked out of the entrance of the cave into the sunlight and immediately signed away the deed of my property. I told myself that the difference was that my grandmother had been born a pessimist.

I walked from the porch of my childhood home to my silver car, and, glancing over the wooden fence towards the goats in the pen, I caught Phil''s eye for the last time. He raised his heavy, horned head with a tuft of grass in his crooked mouth. He watched me as he swallowed the grass and then he swung his tail and lowered his head for another bite.',
  plain_text = 'My grandmother was the sole proprietor of a three room cave, to which we sold tickets and gave tours. She always said, "It''s a funny thing to have built a life upon the absence of Earth". When she died, she left us the cave (my mother had already died in an incident that was unrelated to the cave), and this is how I became the proprietor of one third of a cave which was located just south west of a small town that wasn''t even a tourist destination.

My grandfather, always a pragmatist, found that the work of his evenings revolved around trying to get my grandmother to use the cave for something practical. He was always interested in the yield.

"We can''t just keep giving tours with this little seasonal traffic; bat shit from the floor of the cave won''t miraculously turn it into food," he complained, as he sat at the dining room table, using his fork to prod at white, mushy potatoes. The lumps struck me as oddly resembling the very bat shit which he claimed we couldn''t eat. He shoveled a forkful into his mouth and mashed his chompers up and down. The clumps of bat shit that did not make it past the guard of his lips ended up in his wiry, greasy beard. I gazed at him, wondering how we could squeeze more money out of the emptiness in our backyard.

My grandparents had tried making cheese at one point because cheese and caves go hand in hand like scotch and cellars. They gave it a good go. They accumulated a number of goats. One hairy, black goat, had it not been for movies, would have gotten off scot free from being the devil. But instead, the unlucky goat, who just wanted attention from us children, was painted with the name Phil and cast into a life of neglect, depression, and loneliness. Phil only produced one rind of cheese in his life, and it was never eaten. Instead it was left in the cellar where it grew horns of green mold and later became the feature event of a slow year.

When I grew up, the mountains called me, probably because I had spent so many hours underground. As I stumbled up the rocks, I couldn''t help consider that part of my equity contained a third of a cave. Nonetheless, on my thirtieth birthday, from the peaks of a medium sized mountain, I looked out over small drips of other mountains in this particular range. I studied the shadows from the sun and layers upon layers of rocks and clouds. I had come so far from the cave of my childhood. A memory occurred to me then, as if the thin threads of cirrus clouds were weaving images in my mind like a loom.

I wasn''t sure if the memory was mine or was patched together from television shows, recordings my father had captured, subconscious dreams, etc. I couldn''t figure out why my grandmother had been so happy with nothing at all. In my memory, my grandmother trounced around the kitchen, cooking, surrounded by almost nothing: a few potatoes, a can of corn, a tin of sardines, a rutabaga, the milk from the goats, and some magical ingredients, the name of which she refused to disclose (us children all agreed it was bat shit or scrapings off the hooves of the goats or mashed up hair). As I watched her dance around the kitchen, blissfully ignorant of our poverty, my grandmother, every so often, glanced out the window above the sink at the entrance to our cave, as if waiting for a beast to emerge. One of her idiosyncrasies was that she refused to put the lids of jars back on the jars after she opened them. She also slept with the door to her bedroom open. Perhaps, I remembered, everything, to her, was a cave.

I descended the mountain and went back home and sat in the cave. Although I could have forcedly conjured some revelation by sitting cross legged like a yogi in the cold, damp, dark hollow, underground, I didn''t. Instead my mind felt as empty as the three rooms of the cave. I walked out of the entrance of the cave into the sunlight and immediately signed away the deed of my property. I told myself that the difference was that my grandmother had been born a pessimist.

I walked from the porch of my childhood home to my silver car, and, glancing over the wooden fence towards the goats in the pen, I caught Phil''s eye for the last time. He raised his heavy, horned head with a tuft of grass in his crooked mouth. He watched me as he swallowed the grass and then he swung his tail and lowered his head for another bite.'
WHERE slug = 'the-cave';

-- 3. about the unhinging of her own mind, the Moon.
UPDATE poems SET
  content = 'In 1937, in a beautiful little house in the South of France, a small titmouse resided with a brutish beast. In the crooks and crannies of the idyllic cottage, insulated by their own dreams, they played together, for two surreal years. The titmouse was younger than the beast but this didn''t matter, for, cosmically, she was as old as the Universe and he was just a child, even though his bones creaked like an old man. The titmouse instilled in the beast the memories of a youth he had forgotten entirely. She drew things he had only fathomed but could never before bring to life. They spoke the same language, outside of human vernacular, of course. They played together like children in the sandbox. Sometimes he would find his own fur in a plate of scrambled eggs, a dish which the titmouse had cheekily prepared as she hopped around the kitchen. Other times, the beast would scare the titmouse half to death, at the most inopportune of times, while she was drawing cards from a deck, or stretching her pretty blue feathers, or disentangling a gold necklace from a set of black fishnets. The titmouse pecked at the beast''s fur, jumping all over his body as he rested, snatching a thread here, a thread there, while the beast let out dream filled growls, which sometimes sounded like laughter. She would then take the strands back to her nest, and place them, ever so carefully, in just the right way, so as to form the most magical nest, in which grew the most magical creatures, diagrams, elements, dreams- incarnations that could be seen only as something resembling that which one observes with human eyes to be real but is not entirely real at all. Of course, the strands were just adornments; the strands never comprised the real engineering of the nest.

They would play games together, often hiding, often stowing their animal bodies beneath the floorboards, or just over the eaves of the woven roofed cottage, or behind the drapes which were dark and eerie in the ancient dust of the moonset. In the woods just surrounding them, there was always the danger of feeling the reality of the outside world. The threat of fascism, imprisonment, suffering, were always there, but you would have never known it by the flirtatious and cheeky interplay of the titmouse and the beast. Nonetheless, this is perhaps why they were always playing this game of hiding, unconsciously preparing for a world growing ever dimmer; the darkness surrounded the lit orb around the flame of a dying candle, as they painted through the night, constantly conjuring trickery between the Lovers.

After two years hunters finally came and dragged the beast away. In a fury, clawing at the flesh of the pigs, the beast went down, disappearing into the wild unknown. The titmouse, finding herself alone in the empty little house, started to bleed from her breast, whistling a ghostly tune, as she mourned the beast. She didn''t know if he would ever come back, and she wandered the empty hallways, muttering in French about the Hanged Man, about whether she should sell the house, about the unhinging of her own mind, the Moon.',
  plain_text = 'In 1937, in a beautiful little house in the South of France, a small titmouse resided with a brutish beast. In the crooks and crannies of the idyllic cottage, insulated by their own dreams, they played together, for two surreal years. The titmouse was younger than the beast but this didn''t matter, for, cosmically, she was as old as the Universe and he was just a child, even though his bones creaked like an old man. The titmouse instilled in the beast the memories of a youth he had forgotten entirely. She drew things he had only fathomed but could never before bring to life. They spoke the same language, outside of human vernacular, of course. They played together like children in the sandbox. Sometimes he would find his own fur in a plate of scrambled eggs, a dish which the titmouse had cheekily prepared as she hopped around the kitchen. Other times, the beast would scare the titmouse half to death, at the most inopportune of times, while she was drawing cards from a deck, or stretching her pretty blue feathers, or disentangling a gold necklace from a set of black fishnets. The titmouse pecked at the beast''s fur, jumping all over his body as he rested, snatching a thread here, a thread there, while the beast let out dream filled growls, which sometimes sounded like laughter. She would then take the strands back to her nest, and place them, ever so carefully, in just the right way, so as to form the most magical nest, in which grew the most magical creatures, diagrams, elements, dreams- incarnations that could be seen only as something resembling that which one observes with human eyes to be real but is not entirely real at all. Of course, the strands were just adornments; the strands never comprised the real engineering of the nest.

They would play games together, often hiding, often stowing their animal bodies beneath the floorboards, or just over the eaves of the woven roofed cottage, or behind the drapes which were dark and eerie in the ancient dust of the moonset. In the woods just surrounding them, there was always the danger of feeling the reality of the outside world. The threat of fascism, imprisonment, suffering, were always there, but you would have never known it by the flirtatious and cheeky interplay of the titmouse and the beast. Nonetheless, this is perhaps why they were always playing this game of hiding, unconsciously preparing for a world growing ever dimmer; the darkness surrounded the lit orb around the flame of a dying candle, as they painted through the night, constantly conjuring trickery between the Lovers.

After two years hunters finally came and dragged the beast away. In a fury, clawing at the flesh of the pigs, the beast went down, disappearing into the wild unknown. The titmouse, finding herself alone in the empty little house, started to bleed from her breast, whistling a ghostly tune, as she mourned the beast. She didn''t know if he would ever come back, and she wandered the empty hallways, muttering in French about the Hanged Man, about whether she should sell the house, about the unhinging of her own mind, the Moon.'
WHERE slug = 'about-the-unhinging-of-her-own-mind-the-moon';

-- 4. Joe Strummer's Jib
UPDATE poems SET
  content = 'For Leonora Carrington

No one remembers what it''s like to see a band these days. I mean, sure, you can say, are you into Tom Waits, but really it''s only a semiotic nod, a tip of the hat to hours of lonely listening to the app, man, croon, drunk on the moon and whiskey, into a temporarily inhabited room. No one knows which way the sweat rolls off Joe Strummer''s jib. You really just have to see it to believe it. Who recalls whether it was clockwise or counter clockwise, as Morrison gyrated his hips across the dilapidated stage of LA? No, no one is fan purely and initially by experience alone anymore.

And this is what interaction became: meaningless. Digital numbers whizzing by; spermiotic pilots in the milky cloud of the cosmos. Way too many portals into which one can jam their face. In fact, interaction between humans and their surrounding world became so meaningless that one could not tell advert from entertainment, fake news from real news, real love from manufactured love, even real memories from fake memories. Therefore, a competition was invented in order to determine the winner. It was called The Most Meaningless Competition. It was invented because, of course, at its end, or, shall I say, in the end, as one attempt to sift out the truth, one finds that everything is a measuring contest (a truth only evident through the lens of Western psyche; the Yogis of ancient times, the ones who paid monthly fees towards enlightenment, let''s say, would have never lain their cocks out on the mat- or maybe they would have, but only to stretch them, never to measure).

There were many winners of the competition throughout the years; each winner was forgotten in less time than it takes the processor of a micro neuronic chip to interpret the impression of having experienced some sort of interaction, sort of like the whisper of a ghost on the tiny hairs standing up, at the top of your ear (look how I''m assuming you know how a body feels, POTENTIAL ROBOT).

The competition itself was also forgotten entirely, eventually removed from the canon of history that included those who were still remembered but deceased at sort of a biological level, if you will. Therefore, is it unfortunate that you are remembering something that doesn''t have any existence?

Perhaps. When the world returns, when the cycle repeats itself again, and there is a shitty rock band playing in a smoky bar, in the middle of a snow storm in April, perhaps, then, that''s when the long drip from the corner of a slim crescent moon will finally fall, and cast rings around the puddles of Berlin, meaningless ripples in the silver Wasser.',
  plain_text = 'For Leonora Carrington

No one remembers what it''s like to see a band these days. I mean, sure, you can say, are you into Tom Waits, but really it''s only a semiotic nod, a tip of the hat to hours of lonely listening to the app, man, croon, drunk on the moon and whiskey, into a temporarily inhabited room. No one knows which way the sweat rolls off Joe Strummer''s jib. You really just have to see it to believe it. Who recalls whether it was clockwise or counter clockwise, as Morrison gyrated his hips across the dilapidated stage of LA? No, no one is fan purely and initially by experience alone anymore.

And this is what interaction became: meaningless. Digital numbers whizzing by; spermiotic pilots in the milky cloud of the cosmos. Way too many portals into which one can jam their face. In fact, interaction between humans and their surrounding world became so meaningless that one could not tell advert from entertainment, fake news from real news, real love from manufactured love, even real memories from fake memories. Therefore, a competition was invented in order to determine the winner. It was called The Most Meaningless Competition. It was invented because, of course, at its end, or, shall I say, in the end, as one attempt to sift out the truth, one finds that everything is a measuring contest (a truth only evident through the lens of Western psyche; the Yogis of ancient times, the ones who paid monthly fees towards enlightenment, let''s say, would have never lain their cocks out on the mat- or maybe they would have, but only to stretch them, never to measure).

There were many winners of the competition throughout the years; each winner was forgotten in less time than it takes the processor of a micro neuronic chip to interpret the impression of having experienced some sort of interaction, sort of like the whisper of a ghost on the tiny hairs standing up, at the top of your ear (look how I''m assuming you know how a body feels, POTENTIAL ROBOT).

The competition itself was also forgotten entirely, eventually removed from the canon of history that included those who were still remembered but deceased at sort of a biological level, if you will. Therefore, is it unfortunate that you are remembering something that doesn''t have any existence?

Perhaps. When the world returns, when the cycle repeats itself again, and there is a shitty rock band playing in a smoky bar, in the middle of a snow storm in April, perhaps, then, that''s when the long drip from the corner of a slim crescent moon will finally fall, and cast rings around the puddles of Berlin, meaningless ripples in the silver Wasser.'
WHERE slug = 'joe-strummers-jib';

-- 5. 3 compartments
UPDATE poems SET
  content = 'Here is a compartment suspended in air. There is nothing holding it there. There are no wires, stands, or nets. It is not floating and it is not sitting upon something. It is utterly suspended. It is as if it were in zero gravity but it is not. It is in the shape of a rectangle, much like a train''s boxcar. Although, it is not red, or charcoal, or rusted brown. In fact, it is not any color. The question it invokes is not one of existential nature. It is a question more related to Schrödinger''s cat. Are there but more compartments inside of this suspended compartment like an onion? Or like a submarine? Or like the pages of a book? How does one imagine the guts of a suspended compartment?

Painted in airbrushed, graffiti style lettering on one wall of this compartment are the words, ''Honk Your Lust''. It is a testament to a time when sex was not repressed. It is an indictment of fat, New York style, truck drivers everywhere. It is cue to young lovers and old lovers alike. Flaunt your desire! Tune up your want! Pull down your pants! The rest of the compartment is plain. There is no flare to the carpet. There is a pedestrian feel to the ceiling fan. There aren''t tassels on the lamp shades. Everything else in the compartment is repressed.

The doors to this compartment are saloon style. They swing in and out as the patrons enter and exit. I sit alone at the bar but I am not the outlaw to whom everyone''s eyes flash as he makes any sudden movement. I am the one who dreams about being the outlaw. I imagine myself riding through town at a wild, radical pace, bills flying out behind me, still crisp from the freshly robbed bank. I steal the sheriff''s horse and take his pretty wife as a hostage. When the bartender asks me what else I would like, I don''t know what to say.',
  plain_text = 'Here is a compartment suspended in air. There is nothing holding it there. There are no wires, stands, or nets. It is not floating and it is not sitting upon something. It is utterly suspended. It is as if it were in zero gravity but it is not. It is in the shape of a rectangle, much like a train''s boxcar. Although, it is not red, or charcoal, or rusted brown. In fact, it is not any color. The question it invokes is not one of existential nature. It is a question more related to Schrödinger''s cat. Are there but more compartments inside of this suspended compartment like an onion? Or like a submarine? Or like the pages of a book? How does one imagine the guts of a suspended compartment?

Painted in airbrushed, graffiti style lettering on one wall of this compartment are the words, ''Honk Your Lust''. It is a testament to a time when sex was not repressed. It is an indictment of fat, New York style, truck drivers everywhere. It is cue to young lovers and old lovers alike. Flaunt your desire! Tune up your want! Pull down your pants! The rest of the compartment is plain. There is no flare to the carpet. There is a pedestrian feel to the ceiling fan. There aren''t tassels on the lamp shades. Everything else in the compartment is repressed.

The doors to this compartment are saloon style. They swing in and out as the patrons enter and exit. I sit alone at the bar but I am not the outlaw to whom everyone''s eyes flash as he makes any sudden movement. I am the one who dreams about being the outlaw. I imagine myself riding through town at a wild, radical pace, bills flying out behind me, still crisp from the freshly robbed bank. I steal the sheriff''s horse and take his pretty wife as a hostage. When the bartender asks me what else I would like, I don''t know what to say.'
WHERE slug = '3-compartments';

-- 6. 3 more compartments
UPDATE poems SET
  content = 'You are alerted of this compartment by text message. Your phone softly buzzes on the coffee table and emits a short jingle as a connotation of arrival. You pick it up and swipe the screen. There it is: another compartment. There is text in this compartment. It litters the floors, paints the walls, fogs the air. It is all consuming as you read it. It is digital and harsh. It does not have the parched feeling of paper. There is no heart to it. You place your phone back down on the coffee table. Now you have absorbed this compartment. It has changed you. Its words have altered the direction of your thoughts. Now you are thinking about sex. Now you are thinking of a memory of sex. Now you are thinking about a song in that memory. This compartment has unfolded nicely inside your head. There are others that do not.

Deep within me. Down past the compartments of ex-girlfriends and burned bridges. Way down past the grudges and dislikes and fears. Way, way down underneath the tombs. Way, way, way down there, there is a compartment where I can''t talk. It is not that I won''t talk, it is that I can''t talk. I have eyes and ears and a nose but where my mouth should be, there is not a mouth. There is just skin. Skin and then a chin. The compartment is a room. There is no one else in the room. Except one person. There is one person in the room. She is my mother. She does not talk all the time, nor is she silent all the time. The room is small enough that we have to look at each other. Sometimes I feel where my mouth should be. Sometimes I feel like I''ve never had a mouth. Other times I have a vague memory of it being there. I wonder if I slowly, over a matter of years sewed it shut. I seem to remember using smaller and smaller stitches. Stitches so small that they were invisible to the naked eye. Stitches that dissolved into my skin as the mouth wound healed. There was a faint scar just under my nose. An area where the stubble didn''t grow. A line where I used to draw my fingers in nostalgia. Until one day that line disappeared and I forgot all about it.

This compartment is full of ropes. The ropes are not suspended nor hanging from the ceiling. They are daisy chained and strewn about the floor. They are organized in order of length. The walls and ceiling are slate. The floor is bamboo. What does power look like wafting around the air? Is it a black cloud in the room? Is it a tied up elephant in the corner, it''s arms and legs bound behind it? This compartment is a container for power. It contains power.',
  plain_text = 'You are alerted of this compartment by text message. Your phone softly buzzes on the coffee table and emits a short jingle as a connotation of arrival. You pick it up and swipe the screen. There it is: another compartment. There is text in this compartment. It litters the floors, paints the walls, fogs the air. It is all consuming as you read it. It is digital and harsh. It does not have the parched feeling of paper. There is no heart to it. You place your phone back down on the coffee table. Now you have absorbed this compartment. It has changed you. Its words have altered the direction of your thoughts. Now you are thinking about sex. Now you are thinking of a memory of sex. Now you are thinking about a song in that memory. This compartment has unfolded nicely inside your head. There are others that do not.

Deep within me. Down past the compartments of ex-girlfriends and burned bridges. Way down past the grudges and dislikes and fears. Way, way down underneath the tombs. Way, way, way down there, there is a compartment where I can''t talk. It is not that I won''t talk, it is that I can''t talk. I have eyes and ears and a nose but where my mouth should be, there is not a mouth. There is just skin. Skin and then a chin. The compartment is a room. There is no one else in the room. Except one person. There is one person in the room. She is my mother. She does not talk all the time, nor is she silent all the time. The room is small enough that we have to look at each other. Sometimes I feel where my mouth should be. Sometimes I feel like I''ve never had a mouth. Other times I have a vague memory of it being there. I wonder if I slowly, over a matter of years sewed it shut. I seem to remember using smaller and smaller stitches. Stitches so small that they were invisible to the naked eye. Stitches that dissolved into my skin as the mouth wound healed. There was a faint scar just under my nose. An area where the stubble didn''t grow. A line where I used to draw my fingers in nostalgia. Until one day that line disappeared and I forgot all about it.

This compartment is full of ropes. The ropes are not suspended nor hanging from the ceiling. They are daisy chained and strewn about the floor. They are organized in order of length. The walls and ceiling are slate. The floor is bamboo. What does power look like wafting around the air? Is it a black cloud in the room? Is it a tied up elephant in the corner, it''s arms and legs bound behind it? This compartment is a container for power. It contains power.'
WHERE slug = '3-more-compartments';
